import StoreProvider from "@app/_providers/StoreProvider";
import DesignSystemProvider from "./_providers/DesignSystemProvider";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactElement, ReactNode } from "react";
import type { Metadata } from "next";
import "@shared/theme/style.css";
import DefaultLayout from "./_layouts/DefaultLayout";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Shop Testing Next App",
    description: "Generated by create next app",
};

const RootLayout = ({
    children,
}: Readonly<{
    children: ReactNode;
}>): ReactElement => {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <div className="content">
                    <DesignSystemProvider>
                        <StoreProvider>
                            <DefaultLayout>{children}</DefaultLayout>
                        </StoreProvider>
                    </DesignSystemProvider>
                </div>
            </body>
        </html>
    );
};

export default RootLayout;
