services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shopping-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./backend/app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
